/**
 * YouTube プレイリスト URL のクライアント安全な判定・ID 抽出。
 */

const YOUTUBE_PLAYLIST_ID_RE = /^[a-zA-Z0-9_-]{8,128}$/;

const YOUTUBE_PLAYLIST_HOSTS = new Set([
  'youtube.com',
  'www.youtube.com',
  'm.youtube.com',
  'music.youtube.com',
]);

export type YoutubePlaylistUrlParseResult = {
  playlistId: string;
  canonicalUrl: string;
};

/**
 * YouTube が自動生成する「ミックス／ラジオ」の list ID かどうか。
 * `RD` で始まる（`RD<videoId>` のラジオ、`RDMM`＝マイミックス、`RDEM`／`RDCLAK5uy` 等）ものが該当。
 * これらはトップからサムネイルをクリックした単曲視聴 URL（`watch?v=...&list=RD...&start_radio=1`）に
 * 自動付与されるため、意図しない連続再生の原因になる。
 */
export function isYoutubeAutoGeneratedMixListId(listId: string): boolean {
  return /^RD/.test(listId.trim());
}

export function parseYoutubePlaylistUrl(raw: string): YoutubePlaylistUrlParseResult | null {
  const text = raw.trim();
  if (!text) return null;
  try {
    const url = new URL(text);
    const host = url.hostname.toLowerCase();
    if (!YOUTUBE_PLAYLIST_HOSTS.has(host)) return null;
    const playlistId = url.searchParams.get('list')?.trim() ?? '';
    if (!YOUTUBE_PLAYLIST_ID_RE.test(playlistId)) return null;

    // 単曲視聴 URL（/watch?v=...）に自動生成のミックス／ラジオが付いているだけの場合は、
    // プレイリストとして扱わず単曲選曲へフォールスルーさせる（意図せぬ連続再生の防止）。
    // 明示的な /playlist ページはミックスでも従来どおりプレイリストとして扱う。
    const isExplicitPlaylistPage = url.pathname.toLowerCase() === '/playlist';
    if (!isExplicitPlaylistPage) {
      const hasWatchVideo = (url.searchParams.get('v')?.trim() ?? '') !== '';
      const isStartRadio = url.searchParams.get('start_radio')?.trim() === '1';
      if (hasWatchVideo && (isStartRadio || isYoutubeAutoGeneratedMixListId(playlistId))) {
        return null;
      }
    }

    return {
      playlistId,
      canonicalUrl: `https://www.youtube.com/playlist?list=${encodeURIComponent(playlistId)}`,
    };
  } catch {
    return null;
  }
}

export function isYoutubePlaylistUrl(raw: string): boolean {
  return parseYoutubePlaylistUrl(raw) !== null;
}
